
# sur quel port le serveur démarre
server:
  port: 8080

# Les informations de connexion de la bd

spring:
  profiles:
    active: dev
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com
          issuer-uri: https://securetoken.google.com/projet-integrateur-miage-g08
l3:
  miage:
    webservice:
      rest:
        url: "http://localhost:8081"
